((identifier) @markid)
((type_identifier) @markid)
((type_annotation) @markid)
((property_identifier) @markid)
((shorthand_property_identifier_pattern) @markid)
((shorthand_property_identifier) @markid)
